### ISSUE TITLE
Create a basic login page and navigate to the dashboard page.

### ISSUE THREAD

**Issue by Akash-M** [Akash-M/sap-abap-frontend#2]

**Comment by Prateek057** [comment]
Features/Views/Components to be implemented
Input Fields: 
1. customer ID or mobil phone number
2. password
3. remember password (yes/no)

Functionalities Required: 
1. Login
2. Forgot Remember
3. Become a customer - Redirect to Registration Page

![login-page](https://cloud.githubusercontent.com/assets/5918037/20487567/22f2c632-b004-11e6-93fc-2da3648d1f17.jpg)
